/*
 * Created on 2024-05-16 ( 11:40:51 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.entities;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "Shipment"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="shipment", schema="public" )
public class ShipmentPersistable implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="order_id")
    private Integer    orderId ;

    @Column(name="product_id", length=50)
    private String     productId ;

    @Column(name="quantity")
    private Double     quantity ;

    @Column(name="tracking_id", length=50)
    private String     trackingId ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public ShipmentPersistable() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setOrderId( Integer orderId ) {
        this.orderId = orderId ;
    }
    public Integer getOrderId() {
        return this.orderId;
    }

    public void setProductId( String productId ) {
        this.productId = productId ;
    }
    public String getProductId() {
        return this.productId;
    }

    public void setQuantity( Double quantity ) {
        this.quantity = quantity ;
    }
    public Double getQuantity() {
        return this.quantity;
    }

    public void setTrackingId( String trackingId ) {
        this.trackingId = trackingId ;
    }
    public String getTrackingId() {
        return this.trackingId;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(orderId);
        sb.append("|");
        sb.append(productId);
        sb.append("|");
        sb.append(quantity);
        sb.append("|");
        sb.append(trackingId);
        return sb.toString(); 
    } 

}
