/*
 * Created on 2024-05-15 ( 13:20:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.nse.entities;

import java.io.Serializable;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * JPA entity class for "ProductOrder"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="product_order", schema="public" )
public class ProductOrder implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name="id", nullable=false)
    private Long       id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="product_id", length=50)
    private String     productId ;

    @Column(name="order_status", length=25)
    private String     orderStatus ;

    @Column(name="price")
    private Double     price ;

    @Column(name="quantity")
    private Double     quantity ;


    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public ProductOrder() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    public void setProductId( String productId ) {
        this.productId = productId ;
    }
    public String getProductId() {
        return this.productId;
    }

    public void setOrderStatus( String orderStatus ) {
        this.orderStatus = orderStatus ;
    }
    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setPrice( Double price ) {
        this.price = price ;
    }
    public Double getPrice() {
        return this.price;
    }

    public void setQuantity( Double quantity ) {
        this.quantity = quantity ;
    }
    public Double getQuantity() {
        return this.quantity;
    }

    //--- GETTERS FOR LINKS
    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(id);
        sb.append("|");
        sb.append(productId);
        sb.append("|");
        sb.append(orderStatus);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(quantity);
        return sb.toString(); 
    } 

}
